apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: middleware-redirect-https
  namespace: traefik
spec:
  redirectScheme:
    scheme: https
---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: ir-redirect-https-chiyuki-life
  namespace: traefik
spec:
  entryPoints:
    - web
  routes:
    - match: Host(`app.chiyuki.life`)
      kind: Rule
      services:
        - name: api@internal
          kind: TraefikService
      middlewares:
        - name: middleware-redirect-https