---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sc-mysql-data
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql-data
spec:
  capacity:
    storage: 20Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: sc-mysql-data
  local:
    path: /data/k3s/mysql
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s-s01

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: mysql
  name: pvc-mysql-data
  namespace: mysql
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: sc-mysql-data
  volumeName: pv-mysql-data
  resources:
    requests:
      storage: 20Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: mysql:8
          name: mysql
          env:
            # 这里应该使用 secret，但是在我的 homelab 环境中不需要考虑这些，反正一会要改
            - name: MYSQL_ROOT_PASSWORD
              value: password
          ports:
            - containerPort: 3306
              name: mysql
          volumeMounts:
            - name: mysql-persistent-storage
              mountPath: /var/lib/mysql
          resources:
            limits:
              memory: 2Gi
              cpu: "2"
            requests:
              memory: 1Gi
              cpu: "1"
      volumes:
        - name: mysql-persistent-storage
          persistentVolumeClaim:
            claimName: pvc-mysql-data

---
apiVersion: v1
kind: Service
metadata:
  name: srv-mysql
  namespace: mysql
spec:
  type: NodePort
  selector:
    app: mysql
  ipFamilyPolicy: PreferDualStack
  ipFamilies:
    - IPv4
    - IPv6
  ports:
    - port: 3306
      protocol: TCP
      name: mysql
      targetPort: mysql
      nodePort: 30006
